<?php 
 $path = 'OfferChat_options/OfferChatSettings/MerchantApiCode';
 $key = Mage::getStoreConfig($path);
 if( !empty( $key ) ){
?>
<!--start of Offerchat js code-->
<script type='text/javascript'>var ofc_key = '<?php echo $key; ?>';(function(){ var oc = document.createElement('script'); oc.type = 'text/javascript'; oc.async = true; oc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'www.offerchat.com/offerchat_widget.min.js?r='+ Math.random(); var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(oc, s);}());</script>
<!--end of Offerchat js code-->
 <?php } ?>