<?php 
 $path = 'OfferChat_options/OfferChatSettings/MerchantApiCode';
 $key = Mage::getStoreConfig($path);
 if( !empty( $key ) ){
?>
<!--start of Offerchat js code-->
 <!--start of Offerchat js code--><script type='text/javascript'>var ofc_key = '<?php echo $key; ?>';(function(){  var oc = document.createElement('script'); oc.type = 'text/javascript'; oc.async = true;  oc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'd1cpaygqxflr8n.cloudfront.net/p/js/widget.min.js?r=1';  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(oc, s);}());</script><!--end of Offerchat js code-->
 <?php } ?>
